### ISSUE TITLE
"too many values to unpack (expect 2)" when ran skeleton_to_csgraph

### ISSUE THREAD

**Issue by XDengN** [jni/skan#170] opened 2022-04-19 21:10 UTC
Hi,

I was trying to test the code from https://skeleton-analysis.org/getting_started.html. Everything worked well until I was trying to run `pixel_graph, coordinates = skeleton_to_csgraph(skeleton0)`. It reported `ValueError: too many values to unpack (expected 2)`. I tried on skan's example image and my own image as well. Both reported the same error. How can I resolve this? 

Thanks!

**Comment by XDengN** [comment] 2022-04-19 22:36
I think there might be a bug. According to the text from https://skeleton-analysis.org/getting_started.html, `skeleton_to_csgraph`actually returns three values: pixel_graph, coordinates and degrees. 

But in the source file of csr.py, `skeleton_to_csgraph` is only supposed to return pixel_graph and coordinates. So is expected from the example code: `pixel_graph, coordinates = skeleton_to_csgraph(skeleton0)`. 

Therefore the discrepancy and thus the error warning. 

After I add one more expected return value to the example code, the problem solved. `pixel_graph, coordinates, degrees = skeleton_to_csgraph(skeleton0)`

**Comment by jni** [comment] 2022-04-20 06:23
Hi @XDengN!

I apologise. The issue is that the documentation site shows the latest API from main, but the version you have installed (from pip or conda-forge) contains the 0.10.0 API. I have an issue about this (#158), but haven't been able to get to it.

If you want to follow the docs, you can install skan from main using `pip install -U pip+https://github.com/jni/skan`.

I'm going to close this as it is in a sense a duplicate of #158, but if you have ongoing issues please don't hesitate to reach out again!

**Closed by jni** 2022-04-20 06:23 UTC

**Comment by XDengN** [comment] 2022-04-20 17:58
Hi @jni 

Thank you for your reply. `pip install -U pip+https://github.com/jni/skan` doesn't really work for me. The system says: "Hint: It looks like a path. File 'pip+https://github.com/jni/skan' does not exist."

**Comment by jni** [comment] 2022-04-21 00:31
Oops!!! Sorry I mistyped: `pip install -U git+https://github.com/jni/skan`. I updated the comment.
